language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.6
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.3.0
  - jruby-19mode
  - rbx-2.2.7
  - jruby-9.0.0.0.pre2
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
